sonar.projectKey=subscription-server                                                                            
sonar.sources=src                                                                                                      
sonar.tests=tests                                                                                                      
sonar.python.coverage.reportPaths=coverage.xml
                                                                                                                        
# Exclusions structurelles (pas testables sans infra)                                                                  
sonar.coverage.exclusions=src/database/**,src/settings.py                                                              
                                                                                                                        
# Exclusions de l'analyse statique (fichiers tiers/générés)                                                            
sonar.exclusions=venv/**,migrations/**